// ======================================================== \\
EXTENTIONS = [
  "AutoHotkey Plus",
  "Auto Rename Tag",
  "Better Comments",
  "Error Lens",
  "Fluent Icons",
  "Peacock",
  "Remote - SSH",
  "Remote - SSH: Editing Configuration Files",
  "Remote Explorer",
  "Symbols",
  "Vue 3 Snippets",
  "WSL",
  "ESLint",
  "Extension Pack for Java",
  "Format HTML in PHP",
  "GitLens",
  "Gradle for Java",
  "Import Cost",
  "Path Intellisense",
  "Rainbow CSV",
  "Vue Official",
  "XML Tools",
  "Colorize",
  "CSS Peek",
  "Data Preview",
  "es6-string-html",
  "Ionic",
  "Language Support for Java(TM) by Red Hat",
  "Regex Previewer",
  "Turbo Console Log",
  "GitHub Copilot",
  "PowerShell",
  "Prettier",
  "Regex Previewer",
  "Supermaven",
  "Maven for java",
  "Date & Time",
  "Debugger for Java",
  "Markdown All in One",
  "Laravel Blade Snippets",
  "Laravel Extra IntelliSense",
  "Live Preview",
  "Node.js Modules IntelliSense",
  "npm IntelliSense",
  "Tailwind CSS IntelliSense",
  "PHP IntelliSense",
  "Project Manager for Java",
  "Test Runner for Java",
  // ======================================================== \\
  // Custom Extensions \\
  // ======================================================== \\
  "Night Owl",
  "One Dark Pro",
  "Cobalt Next",
  "HackTheBox",
]