// ======================================================== \\
EXTENTIONS = [
  "Auto Rename Tag",
  "Better Comments",
  "Error Lens",
  "Fluent Icons",
  "Peacock",
  "Remote - SSH",
  "Remote - SSH: Editing Configuration Files",
  "Remote Explorer",
  "Symbols",
  "Vue 3 Snippets",
  "WSL",
  "ESLint",
  "Format HTML in PHP",
  "GitLens",
  "Import Cost",
  "Path Intellisense",
  "Rainbow CSV",
  "Vue Official",
  "XML Tools",
  "Colorize",
  "CSS Peek",
  "Data Preview",
  "es6-string-html",
  "Ionic",
  "Regex Previewer",
  "Turbo Console Log",
  "GitHub Copilot",
  "PowerShell",
  "Prettier",
  "Regex Previewer",
  "Supermaven",
  "Date & Time",  
]